apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cl
  labels:
    app: api-cl
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: api-cl
    tags.datadoghq.com/version: "1.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cl
  template:
    metadata:
      labels:
        app: api-cl
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: api-cl
        tags.datadoghq.com/version: "1.2"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.39.0
    spec:
      containers:
      - name: api-cl
        image: vinicpires/api_clinica:SHORT_SHA
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-datasource-secret
              key: password
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-datasource-secret
              key: username
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: spring-datasource-secret
              key: url
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_APPSEC_ENABLED
          value: "true"
        - name: DD_IAST_ENABLED
          value: "true"
        - name: DD_APPSEC_SCA_ENABLED
          value: "true"

--- 

apiVersion: v1
kind: Service
metadata:
  name: api-cl-service
  labels:
    app: api-cl
spec:
  selector:
    app: api-cl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-cl-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "cloudflare-cluster-issuer"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://clinica-frontend.k8s.lab4ever.xyz"
    nginx.ingress.kubernetes.io/cors-allow-headers: "x-datadog-trace-id, x-datadog-parent-id, x-datadog-origin, x-datadog-sampling-priority, traceparent"
spec:
  rules:
    - host: api-cl.k8s.lab4ever.xyz  # Substitua pelo seu domínio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-cl-service
                port:
                  number: 80
  tls:
    - hosts:
        - api-cl.k8s.lab4ever.xyz
      secretName: api-cl-tls
