name: Deploy app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Get commit short sha
        id: vars
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_clinica:${{ env.SHORT_SHA }}

      - name: Change yaml image attribute value.
        run: |
          SHORT_SHA="${{ env.SHORT_SHA }}"

          echo "Short SHA: $SHORT_SHA"

          sed -i "s|api_clinica:.*|api_clinica:${SHORT_SHA}|g" manifests/api_clinica.yaml

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          mkdir $HOME/.kube   
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
          kubectl apply -f manifests/api_clinica.yaml
